new Application.ViewController({
  //setting the parent as Application will cause
  //Application.setView(this) to be called each
  //time a route is matched on this ViewController
  parent: Application,
  //module.routes is set in the output file generated by lumbar
  routes: module.routes,
  infiniteScroll: function() {
    var view = new Application.Views['examples/infinite-scroll'];
    this.setView(view);
  },
  fastClick: function() {
    var view = new Application.Views['examples/fast-click'];
    this.setView(view);
  },
  tapHighlight: function() {
    var view = new Application.Views['examples/tap-highlight'];
    this.setView(view);
  }
});
