new Application.ViewController({
  //setting the parent as Application will cause
  //Application.setView(this) to be called each
  //time a route is matched on this ViewController
  parent: Application,
  //module.routes is set in the output file generated by lumbar
  routes: module.routes,
  index: function() {
    var view = new Application.Views['hello-world/index'];
    this.setView(view);
  }
});